### ISSUE TITLE
Not Launching on Neo-Forge 1.20.4 V.20.4.164

### ISSUE THREAD

**Issue by Desenrrollado** [nvb-uy/Necronomicon#3]
![Screenshot_1](https://github.com/nvb-uy/Necronomicon/assets/92115460/b71d7816-ed02-4127-ae99-4f124ccd6dd0)

Issue as described. It treats it as if Neo-Forge isn't installed. Asking for Forge exclusively despite it being compatible with both.

Crash: 
[crash-2024-02-20_17.34.20-fml.txt](https://github.com/nvb-uy/Necronomicon/files/14352557/crash-2024-02-20_17.34.20-fml.txt)
Latest Log: 
[latest.log](https://github.com/nvb-uy/Necronomicon/files/14352567/latest.log)
Debug Log: 
[debug.log](https://github.com/nvb-uy/Necronomicon/files/14352573/debug.log)

**Comment by nvb-uy** [comment]
Yes, Necronomicon is a forge mod and only supports NeoForge up to 1.20.1.

This is an issue with the tagging system from CF, I cannot tag it compatible with "x loader but only in y version".
Necronomicon only works with NeoForge on 1.20.1 because NeoForge 1.20.1 supports Forge mods natively. I will not support 1.20.2/3/4 NeoForge until 1.21 releases as I'm staying on 1.20.1 for my projects.

**Comment by Desenrrollado** [comment]
I appreciate the clarification. Sorry for bothering in any case. I was definitely confused due to the labeling on Modrinth, and both Curse-Forge also indicating that it also had support for Neo-forge. 

Yet it was doing that. I just like to test on newer versions from time to time.

Most people are staying on 1.20.1 until a massive update drops.  Even I am.
